name: Create and Publish Docker Image

on:
  workflow_dispatch:  # Allows manual triggering from Github portal.

jobs:
  create-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

      - name: Build full project and Docker image.
        run: npm run docker

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy Docker image to GHCR.
        run: |
          docker tag hone-server ghcr.io/${{ github.actor }}/hone-server:latest
          docker push ghcr.io/${{ github.actor }}/hone-server:latest