name: Rollback Production to Previous Version

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Roll back production to previous version
        uses: DecentAppsNet/rollback@v1
        with:
          app-name: ${{ vars.APP_NAME }}
          api-key: ${{ secrets.DECENT_API_KEY }}